<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "{{%chi_phi}}".
 *
 * @property int $id
 * @property string|null $name
 * @property float|null $so_tien
 *
 * @property ChiTietChiPhi[] $chiTietChiPhis
 */
class ChiPhi extends \yii\db\ActiveRecord
{
    const CHI_PHI_MOI_GIOI = 'Chi phí môi giới';
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%chi_phi}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['so_tien'], 'number'],
            [['name'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'so_tien' => 'So Tien',
        ];
    }

    /**
     * Gets query for [[ChiTietChiPhis]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getChiTietChiPhis()
    {
        return $this->hasMany(ChiTietChiPhi::className(), ['chi_phi_id' => 'id']);
    }
    public function beforeSave($insert)
    {
        if($this->user_id == '' || is_null($this->user_id))
            $this->user_id = Yii::$app->user->id;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
