<?php

namespace backend\models;

use common\models\User;
use Yii;

/**
 * This is the model class for table "{{%chi_tiet_hoa_don}}".
 *
 * @property int $id
 * @property int|null $hoa_don_id
 * @property string|null $created
 * @property int|null $user_id
 * @property int|null $dich_vu_id
 * @property float|null $don_gia
 * @property int|null $so_luong
 * @property string|null $don_vi_tinh
 * @property float|null $thanh_tien
 * @property int|null $chi_so_cu
 *
 * @property HoaDon $hoaDon
 * @property ThietLapGia $dichVu
 * @property User $user
 */
class ChiTietHoaDon extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%chi_tiet_hoa_don}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['hoa_don_id', 'user_id', 'dich_vu_id', 'chi_so_cu', 'so_luong'], 'integer'],
            [['created'], 'safe'],
            [['don_gia', 'thanh_tien'], 'number'],
            [['don_vi_tinh'], 'string', 'max' => 20],
            [['hoa_don_id'], 'exist', 'skipOnError' => true, 'targetClass' => HoaDon::className(), 'targetAttribute' => ['hoa_don_id' => 'id']],
            [['dich_vu_id'], 'exist', 'skipOnError' => true, 'targetClass' => ThietLapGia::className(), 'targetAttribute' => ['dich_vu_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'hoa_don_id' => 'Hoa Don ID',
            'created' => 'Created',
            'user_id' => 'User ID',
            'dich_vu_id' => 'Dich Vu ID',
            'don_gia' => 'Don Gia',
            'so_luong' => 'So Luong',
            'don_vi_tinh' => 'Don Vi Tinh',
            'thanh_tien' => 'Thanh Tien',
            'chi_so_cu' => 'Chi So Cu',
        ];
    }

    /**
     * Gets query for [[HoaDon]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getHoaDon()
    {
        return $this->hasOne(HoaDon::className(), ['id' => 'hoa_don_id']);
    }

    /**
     * Gets query for [[DichVu]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDichVu()
    {
        return $this->hasOne(ThietLapGia::className(), ['id' => 'dich_vu_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    public function beforeSave($insert)
    {
        if($insert && ($this->created == '' || is_null($this->created))){
            $this->created = date("Y-m-d H:i:s");
        }
        if($this->user_id == '' || is_null($this->user_id))
            $this->user_id = Yii::$app->user->id;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
