<?php

namespace backend\models;

use common\models\User;
use Yii;

/**
 * This is the model class for table "{{%chi_tiet_phieu_yeu_cau_giao_hang}}".
 *
 * @property int $id
 * @property int|null $field_phieu_yeu_cau_giao_id
 * @property int|null $field_don_hang_id
 * @property int|null $don_hang_ky_gui_id
 * @property int|null $user_id
 * @property int|null $field_don_hang_old_id
 * @property string|null $created
 *
 * @property User $user
 * @property PhieuYeuCauGiao $fieldPhieuYeuCauGiao
 */
class ChiTietPhieuYeuCauGiaoHang extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%chi_tiet_phieu_yeu_cau_giao_hang}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['field_phieu_yeu_cau_giao_id', 'field_don_hang_id', 'user_id'], 'integer'],
            [['created', 'don_hang_ky_gui_id', 'field_phieu_yeu_cau_giao_id', 'field_don_hang_old_id'], 'safe'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['field_phieu_yeu_cau_giao_id'], 'exist', 'skipOnError' => true, 'targetClass' => PhieuYeuCauGiao::className(), 'targetAttribute' => ['field_phieu_yeu_cau_giao_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'field_phieu_yeu_cau_giao_id' => 'Field Phieu Yeu Cau Giao ID',
            'field_don_hang_id' => 'Field Don Hang ID',
            'user_id' => 'User ID',
            'created' => 'Created',
        ];
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * Gets query for [[FieldPhieuYeuCauGiao]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getFieldPhieuYeuCauGiao()
    {
        return $this->hasOne(PhieuYeuCauGiao::className(), ['id' => 'field_phieu_yeu_cau_giao_id']);
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        if($insert)
            $this->created = date("Y-m-d H:i:s");
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
