<?php

namespace backend\models;

use common\models\User;
use Yii;

/**
 * This is the model class for table "{{%dia_chi_nhan_hang}}".
 *
 * @property int $id
 * @property string|null $thong_tin_dia_chi
 * @property string|null $ghi_chu
 * @property int|null $user_id
 * @property int|null $mac_dinh
 * @property int|null $active
 * @property int|null $dia_chi_nhan_hang_old_nid
 * @property string|null $ho_ten_nguoi_nhan
 * @property string|null $dien_thoai_nguoi_nhan
 * @property string|null $created
 * @property string|null $updated
 *
 * @property User $user
 * @property DonHang[] $donHangs
 */
class DiaChiNhanHang extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%dia_chi_nhan_hang}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['thong_tin_dia_chi', 'ghi_chu'], 'string'],
            [['user_id', 'mac_dinh', 'active'], 'integer'],
            [['created', 'updated', 'dia_chi_nhan_hang_old_nid'], 'safe'],
            [['ho_ten_nguoi_nhan'], 'string', 'max' => 100],
            [['dien_thoai_nguoi_nhan'], 'string', 'max' => 20],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'thong_tin_dia_chi' => 'Thong Tin Dia Chi',
            'ghi_chu' => 'Ghi Chu',
            'user_id' => 'User ID',
            'mac_dinh' => 'Mac Dinh',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function beforeSave($insert)
    {
        if($insert)
            $this->created = date("Y-m-d H:i:s");
        else
            $this->updated = date("Y-m-d H:i:s");

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * Gets query for [[DonHangs]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDonHangs()
    {
        return $this->hasMany(DonHang::className(), ['dia_chi_nhan_hang_id' => 'id']);
    }
}
