<?php

namespace backend\models;

use common\models\User;
use Yii;

/**
 * This is the model class for table "qlcvsd_giao_dich".
 *
 * @property int $id
 * @property int|null $khach_hang_id
 * @property string|null $loai_giao_dich
 * @property string|null $trang_thai_giao_dich
 * @property float|null $tong_tien
 * @property int|null $active
 * @property float|null $so_tien_giao_dich
 * @property string|null $ghi_chu
 * @property string|null $noi_dung_chuyen_khoan
 * @property int|null $user_id
 * @property int|null $ma_id_casso
 * @property string|null $created
 * @property string|null $anh_chuyen_khoan
 * @property string|null $ma_qr
 * @property int|null $giao_dich_old_id
 * @property int|null $phong_khach_id
 * @property int|null $hoa_don_id
 *
 * @property HoaDon $hoaDon
 * @property PhongKhach $phongKhach
 * @property User $khachHang
 * @property User $user
 * @property TrangThaiGiaoDich[] $trangThaiGiaoDiches
 */
class GiaoDich extends \yii\db\ActiveRecord
{
    const KHOI_TAO = 'Khởi tạo';
    const HOAN_THANH = 'Hoàn thành';
    const THANH_CONG = 'Thành công';
    const KHONG_THANH_CONG = 'Không thành công';
    const CHO_DUYET_HUY = 'Chờ duyệt hủy';
    const DA_HUY = 'Đã hủy';
    const THANH_TOAN_HOP_DONG = 'Thanh toán hợp đồng';
    const PHI_MOI_GIOI = 'Phí môi giới';
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'qlcvsd_giao_dich';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['khach_hang_id', 'active', 'user_id', 'giao_dich_old_id', 'phong_khach_id', 'hoa_don_id','ma_id_casso'], 'integer'],
            [['trang_thai_giao_dich', 'loai_giao_dich', 'ghi_chu','noi_dung_chuyen_khoan'], 'string'],
            [['tong_tien', 'so_tien_giao_dich'], 'number'],
            [['created','trang_thai_giao_dich','ma_id_casso','noi_dung_chuyen_khoan','ghi_chu'], 'safe'],
            [['anh_chuyen_khoan', 'ma_qr'], 'string', 'max' => 300],
            [['hoa_don_id'], 'exist', 'skipOnError' => true, 'targetClass' => HoaDon::className(), 'targetAttribute' => ['hoa_don_id' => 'id']],
            [['phong_khach_id'], 'exist', 'skipOnError' => true, 'targetClass' => PhongKhach::className(), 'targetAttribute' => ['phong_khach_id' => 'id']],
            [['khach_hang_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['khach_hang_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'khach_hang_id' => 'Khach Hang ID',
            'trang_thai_giao_dich' => 'Trang Thai Giao Dich',
            'loai_giao_dich' => 'Loai Giao Dich',
            'tong_tien' => 'Tong Tien',
            'active' => 'Active',
            'so_tien_giao_dich' => 'So Tien Giao Dich',
            'ghi_chu' => 'Ghi Chu',
            'user_id' => 'User ID',
            'created' => 'Created',
            'giao_dich_old_id' => 'Giao Dich Old ID',
            'phong_khach_id' => 'Phong Khach ID',
            'anh_chuyen_khoan' => 'Anh Chuyen Khoan',
            'ma_qr' => 'Ma Qr',
            'hoa_don_id' => 'Hoa Don ID',
        ];
    }

    /**
     * Gets query for [[PhongKhach]].
     *
     * @return \yii\db\ActiveQuery
     */

    public function getHoaDon()
    {
        return $this->hasOne(HoaDon::className(), ['id' => 'hoa_don_id']);
    }
    public function getPhongKhach()
    {
        return $this->hasOne(PhongKhach::className(), ['id' => 'phong_khach_id']);
    }

    /**
     * Gets query for [[KhachHang]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getKhachHang()
    {
        return $this->hasOne(User::className(), ['id' => 'khach_hang_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    public function beforeSave($insert)
    {
        if($insert && ($this->created == '' || is_null($this->created))){
            $this->created = date("Y-m-d H:i:s");
        }
        if($this->user_id == '' || is_null($this->user_id))
            $this->user_id = Yii::$app->user->id;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function afterSave($insert, $changedAttributes)
    {
        if ($insert){
            $model = new TrangThaiGiaoDich();
            $model->giao_dich_id = $this->id;
            $model->trang_thai = $this->trang_thai_giao_dich;
            $model->save();
        }

        parent::afterSave($insert, $changedAttributes);
    }

    public function afterUpdate()
    {
        $hoaDon = HoaDon::findOne($this->hoa_don_id);
        if (!is_null($hoaDon)) {
            $hoaDon->updateAttributes([
                'da_thanh_toan'=>$this->so_tien_giao_dich
            ]);
            if($hoaDon->da_thanh_toan == $hoaDon->tong_tien){
                $hoaDon->updateAttributes([
                    'trang_thai'=>HoaDon::DA_THANH_TOAN,
                ]);
                $hoaDon->afterUpdate();
            }
        }
        $model = new TrangThaiGiaoDich();
        $model->giao_dich_id = $this->id;
        $model->trang_thai = $this->trang_thai_giao_dich;
        $model->save();
    }
}
