<?php

namespace backend\models;

use common\models\myAPI;
use common\models\User;
use Yii;

/**
 * This is the model class for table "qlcvsd_hoa_don".
 *
 * @property int $id
 * @property int|null $user_id
 * @property string|null $created
 * @property int|null $thang
 * @property int|null $nam
 * @property int|null $phong_khach_id
 * @property float|null $tien_phong
 * @property float|null $chi_phi_dich_vu
 * @property float|null $tong_tien
 * @property float|null $da_thanh_toan
 * @property int|null $chot_hoa_don
 * @property int|null $active
 * @property int|null $so_nguoi
 * @property string|null $trang_thai
 * @property string|null $ma_hoa_don
 *
 * @property ChiTietHoaDon[] $chiTietHoaDons
 * @property PhongKhach $phongKhach
 * @property User $user
 */
class HoaDon extends \yii\db\ActiveRecord
{
    const CHUA_THANH_TOAN = 'Chưa thanh toán';
    const DA_THANH_TOAN = 'Đã thanh toán';
    const HOAN_THANH = 'Hoàn thành';
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'qlcvsd_hoa_don';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'thang', 'nam', 'phong_khach_id', 'chot_hoa_don', 'active'], 'integer'],
            [['created','trang_thai','ma_hoa_don','so_nguoi'], 'safe'],
            [['tien_phong', 'chi_phi_dich_vu', 'tong_tien', 'da_thanh_toan'], 'number'],
            [['phong_khach_id'], 'exist', 'skipOnError' => true, 'targetClass' => PhongKhach::className(), 'targetAttribute' => ['phong_khach_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'created' => 'Created',
            'thang' => 'Thang',
            'nam' => 'Nam',
            'phong_khach_id' => 'Phong Khach ID',
            'tien_phong' => 'Tien Phong',
            'chi_phi_dich_vu' => 'Chi Phi Dich Vu',
            'tong_tien' => 'Tong Tien',
            'da_thanh_toan' => 'Da Thanh Toan',
            'chot_hoa_don' => 'Chot Hoa Don',
            'active' => 'Active',
        ];
    }

    /**
     * Gets query for [[ChiTietHoaDons]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getChiTietHoaDons()
    {
        return $this->hasMany(ChiTietHoaDon::className(), ['hoa_don_id' => 'id']);
    }

    /**
     * Gets query for [[PhongKhach]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPhongKhach()
    {
        return $this->hasOne(PhongKhach::className(), ['id' => 'phong_khach_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    public function printBill($params)
    {
        $cauHinh = CauHinh::findOne(['ghi_chu'=>'in_hoa_don'])->content;
        $cauHinh = str_replace('{thang}',$params['thang'],$cauHinh);
        $cauHinh = str_replace('{nam}',$params['nam'],$cauHinh);
        $cauHinh = str_replace('{ten_khach_hang}',$params['ten_khach_hang'],$cauHinh);
        $cauHinh = str_replace('{so_dien_thoai}',$params['so_dien_thoai'],$cauHinh);
        $cauHinh = str_replace('{phong}',$params['phong'],$cauHinh);
        $cauHinh = str_replace('{toa_nha}',$params['toa_nha'],$cauHinh);
        $cauHinh = str_replace('{da_thanh_toan}',$params['da_thanh_toan'],$cauHinh);
        $cauHinh = str_replace('{bang}',$params['bang'],$cauHinh);
        $cauHinh = str_replace('{so_tien_no}',$params['so_tien_no'],$cauHinh);
        $cauHinh = str_replace('{so_tien_phai_tra}',$params['so_tien_phai_tra'],$cauHinh);
        $cauHinh = str_replace('{tong_cong}',$params['tong_cong'],$cauHinh);

        return $cauHinh;
    }
    public function beforeSave($insert)
    {
        if($insert && ($this->created == '' || is_null($this->created))){
            $this->created = date("Y-m-d H:i:s");
        }
        if($this->user_id == '' || is_null($this->user_id))
            $this->user_id = Yii::$app->user->id;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function afterSave($insert, $changedAttributes)
    {
        if ($insert){
            //Luu trang thai hoa don
            $this->afterUpdate();

            //Luu chi tiet nguoi o cung
            $oCungs = NguoiOCung::find()->andFilterWhere(['hop_dong_id'=>$this->phong_khach_id])->all();
            foreach ($oCungs as $oCung){
                $chiTiet = new ChiTietOCung();
                $chiTiet->hoa_don_id = $this->id;
                $chiTiet->nguoi_o_cung_id = $oCung->id;
                $chiTiet->save();
            }
            $this->updateAttributes([
                'so_nguoi' => count($oCungs) + 1
            ]);
            $this->createChiTiet();
        }

        parent::afterSave($insert, $changedAttributes);
    }

    public function afterUpdate()
    {
        $model = new TrangThaiHoaDon();
        $model->hoa_don_id = $this->id;
        $model->trang_thai = $this->trang_thai;
        $model->save();
    }
    public function createChiTiet()
    {
        $hopDong = PhongKhach::findOne($this->phong_khach_id);
        $loai = $hopDong->loai_hop_dong;
        if ($loai != 'thang'){
            return;
        }
        $dichVus = ThietLapGia::find()->all();
        $quanLyHoaDon = QuanLyHoaDon::findOne(['id'=>$this->id]);
        $phong = DanhMuc::findOne($quanLyHoaDon->phong_id);
        $giaDichVus = json_decode($phong->gia_dich_vu, true);
        $phiDichVu = 0;
        foreach ($dichVus as $dichVu){
            $model = ChiTietHoaDon::find()
                ->andFilterWhere(['hoa_don_id'=>$this->id])
                ->andFilterWhere(['dich_vu_id'=>$dichVu->id])->one();
            if (!is_null($model)){
                $phiDichVu += $model->thanh_tien;
                continue;
            }
            $chiTiet = new ChiTietHoaDon();
            $chiTiet->hoa_don_id = $this->id;
            $chiTiet->dich_vu_id = $dichVu->id;
            $chiTiet->so_luong = 0;
            $chiTiet->chi_so_cu = 0;
            $chiTiet->thanh_tien = 0;
            foreach ($giaDichVus as $giaDichVu){
                if ($giaDichVu['label'] == $dichVu->name){
                    $chiTiet->thanh_tien = intval($giaDichVu['value']);
                }
            }
            if ($dichVu->name == 'Nước'){
                $chiTiet->chi_so_cu = $phong->so_nuoc;
                $chiTiet->thanh_tien = $quanLyHoaDon->so_nguoi * $phong->gia_nuoc_nguoi;
            }elseif ($dichVu->name == 'Điện'){
                $chiTiet->chi_so_cu = $phong->so_dien;
            }
            $chiTiet->save();
            $phiDichVu += $chiTiet->thanh_tien;
        }
        $this->updateAttributes([
            'chi_phi_dich_vu' => $phiDichVu,
            'tong_tien' => $this->tien_phong + $phiDichVu
        ]);
    }
    public function updateOCung()
    {
        $hoaDons = HoaDon::find()
            ->andFilterWhere(['active'=>1])
            ->andFilterWhere(['phong_khach_id'=>$this->phong_khach_id])
            ->andFilterWhere(['>','id',$this->id])->all();
        //Xoa het chi tiet o cung hien co
        foreach ($hoaDons as $hoaDon){
            $details = ChiTietOCung::findAll(['hoa_don_id'=>$hoaDon->id]);
            if (count($details) > 0){
                foreach ($details as $item){
                    $item->delete();
                }
            }
        }
        //Them vao theo hoa don hien tai
        $chiTiets = ChiTietOCung::findAll(['hoa_don_id'=>$this->id]);
        $this->updateAttributes([
            'so_nguoi'=>count($chiTiets)+1
        ]);
        if (count($chiTiets)>0){
            foreach ($hoaDons as $hoaDon){
                foreach ($chiTiets as $item){
                    $detail = new ChiTietOCung();
                    $detail->hoa_don_id = $hoaDon->id;
                    $detail->nguoi_o_cung_id = $item->nguoi_o_cung_id;
                    $detail->save();
                }
            }
        }
    }
}
