<?php

namespace backend\models;

use common\models\User;
use Yii;

/**
 * This is the model class for table "{{%khieu_nai}}".
 *
 * @property int $id
 * @property string|null $titlte
 * @property string|null $field_noi_dung_khieu_nai
 * @property string|null $field_trang_thai_khieu_nai
 * @property string|null $field_nguoi_nhap_phan_hoi
 * @property int|null $field_don_hang_id
 * @property string|null $field_anh_khieu_nai
 * @property int|null $field_active
 * @property int|null $user_id
 * @property string|null $created
 *
 * @property DonHang $fieldDonHang
 * @property User $user
 */
class KhieuNai extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%khieu_nai}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['field_noi_dung_khieu_nai', 'field_trang_thai_khieu_nai', 'field_nguoi_nhap_phan_hoi', 'field_anh_khieu_nai'], 'string'],
            [['field_don_hang_id', 'field_active', 'user_id'], 'integer'],
            [['created'], 'safe'],
            [['titlte'], 'string', 'max' => 100],
            [['field_don_hang_id'], 'exist', 'skipOnError' => true, 'targetClass' => DonHang::className(), 'targetAttribute' => ['field_don_hang_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'titlte' => 'Titlte',
            'field_noi_dung_khieu_nai' => 'Field Noi Dung Khieu Nai',
            'field_trang_thai_khieu_nai' => 'Field Trang Thai Khieu Nai',
            'field_nguoi_nhap_phan_hoi' => 'Field Nguoi Nhap Phan Hoi',
            'field_don_hang_id' => 'Field Don Hang ID',
            'field_anh_khieu_nai' => 'Field Anh Khieu Nai',
            'field_active' => 'Field Active',
            'user_id' => 'User ID',
            'created' => 'Created',
        ];
    }

    /**
     * Gets query for [[FieldDonHang]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getFieldDonHang()
    {
        return $this->hasOne(DonHang::className(), ['id' => 'field_don_hang_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function beforeSave($insert)
    {
        if($insert)
            $this->created = date("Y-m-d H:i:s");
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
