<?php

namespace backend\models;

use common\models\User;
use Yii;

/**
 * This is the model class for table "{{%phieu_chi}}".
 *
 * @property int $id
 * @property int|null $thang
 * @property int|null $nam
 * @property int|null $active
 * @property int|null $user_id
 * @property int|null $toa_nha_id
 * @property float|null $tong_tien
 * @property string|null $created
 *
 * @property ChiTietChiPhi[] $chiTietChiPhis
 * @property User $user
 * @property DanhMuc $danhMuc
 */
class PhieuChi extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%phieu_chi}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['thang', 'nam', 'active', 'user_id'], 'integer'],
            [['tong_tien'], 'number'],
            [['created'], 'string'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['toa_nha_id'], 'exist', 'skipOnError' => true, 'targetClass' => DanhMuc::className(), 'targetAttribute' => ['toa_nha_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'thang' => 'Thang',
            'nam' => 'Nam',
            'active' => 'Active',
            'user_id' => 'User ID',
            'tong_tien' => 'Tong Tien',
        ];
    }

    /**
     * Gets query for [[ChiTietChiPhis]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getChiTietChiPhis()
    {
        return $this->hasMany(ChiTietChiPhi::className(), ['phieu_chi_id' => 'id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    /**
     * Gets query for [[DanhMuc]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDanhMuc()
    {
        return $this->hasOne(DanhMuc::className(), ['id' => 'toa_nha_id']);
    }
    public function beforeSave($insert)
    {
        if($insert && ($this->created == '' || is_null($this->created))){
            $this->created = date("Y-m-d H:i:s");
        }
        if($this->user_id == '' || is_null($this->user_id))
            $this->user_id = Yii::$app->user->id;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function afterSave($insert, $changedAttributes)
    {
        if ($insert){
            $thangTruoc = $this->thang - 1 == 0 ? 12 : $this->thang - 1;
            $namTruoc = $thangTruoc == 12 ? $this->nam - 1 : $this->nam;

            $query = QuanLyPhongKhach::find()
                ->where(['toa_nha_id' => $this->toa_nha_id, 'active' => 1])
                ->andWhere(['>','so_tien_moi_gioi',0])
                ->andWhere(['MONTH(thoi_gian_hop_dong_tu)' => $thangTruoc])
                ->andWhere(['YEAR(thoi_gian_hop_dong_tu)' => $namTruoc]);

            $tongTienQuery = clone $query;
            $daThanhToanQuery = clone $query;

            $tongTien = $tongTienQuery->sum('so_tien_moi_gioi');
            $daThanhToan = $daThanhToanQuery->sum('da_thanh_toan_moi_gioi');

            $chiPhis = ChiPhi::find()->all();
            foreach ($chiPhis as $item) {
                $chiTiet = new ChiTietChiPhi();
                $chiTiet->phieu_chi_id = $this->id;
                $chiTiet->chi_phi_id = $item->id;
                $chiTiet->so_tien = $item->so_tien;
                if($item->id == 1){
                    $chiTiet->so_tien = $tongTien;
                    $chiTiet->da_thanh_toan = $daThanhToan;
                }
                $chiTiet->ten_chi_phi = $item->name;
                $chiTiet->save();
            }
        }

        parent::afterSave($insert, $changedAttributes);
    }
}
