<?php

namespace backend\models;

use common\models\myActiveRecord;
use common\models\User;
use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%product}}".
 *
 * @property int $id
 * @property string|null $product_id
 * @property string|null $shop_id
 * @property string|null $content
 * @property int|null $user_id
 * @property string|null $created
 * @property string|null $link_product
 * @property string|null $shop_link
 * @property string|null $keyword
 * @property string|null $string_json
 * @property string|null $nguon
 * @property string|null $domain
 * @property string|null $name
 * @property string|null $string_json_vi
 * @property int|null $product_old_id
 *
 * @property ChiTietDonHang[] $chiTietDonHangs
 * @property User $user
 */

class Product extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%product}}';
    }

    /**Product
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['content', 'link_product', 'shop_link', 'string_json', 'name', 'string_json_vi'], 'string'],
            [['user_id', 'product_old_id'], 'safe'],
            [['created', 'keyword'], 'safe'],
            [['product_id', 'shop_id', 'nguon', 'domain'], 'string', 'max' => 100],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'product_id' => 'Product ID',
            'shop_id' => 'Shop ID',
            'content' => 'Content',
            'user_id' => 'User ID',
            'created' => 'Created',
            'link_product' => 'Link Product',
            'shop_link' => 'Shop Link',
            'string_json' => 'String Json',
            'nguon' => 'Nguon',
            'domain' => 'Domain',
            'name' => 'Name',
            'string_json_vi' => 'String Json Vi',
            'product_old_id' => 'Product Old ID',
        ];
    }

    /**
     * Gets query for [[ChiTietDonHangs]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getChiTietDonHangs()
    {
        return $this->hasMany(ChiTietDonHang::className(), ['product_id' => 'id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function beforeSave($insert)
    {
        if($insert)
            $this->created = date("Y-m-d H:i:s");
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
