<?php

namespace backend\models;

use common\models\User;
use Yii;

/**
 * This is the model class for table "{{%thong_bao}}".
 *
 * @property int $id
 * @property int|null $nguoi_nhan_thong_bao_id
 * @property int|null $da_xem
 * @property string|null $route
 * @property string|null $params
 * @property string|null $ghi_chu
 * @property string|null $created
 * @property string|null $title
 * @property int|null $user_id
 *
 * @property User $nguoiNhanThongBao
 * @property User $user
 */
class ThongBao extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%thong_bao}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nguoi_nhan_thong_bao_id', 'da_xem', 'user_id'], 'integer'],
            [['ghi_chu'], 'string'],
            [['created', 'title'], 'safe'],
            [['route', 'params'], 'string', 'max' => 100],
            [['nguoi_nhan_thong_bao_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['nguoi_nhan_thong_bao_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nguoi_nhan_thong_bao_id' => 'Nguoi Nhan Thong Bao ID',
            'da_xem' => 'Da Xem',
            'route' => 'Route',
            'params' => 'Params',
            'ghi_chu' => 'Ghi Chu',
            'created' => 'Created',
            'user_id' => 'User ID',
        ];
    }

    /**
     * Gets query for [[NguoiNhanThongBao]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getNguoiNhanThongBao()
    {
        return $this->hasOne(User::className(), ['id' => 'nguoi_nhan_thong_bao_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function beforeSave($insert)
    {
        if($insert)
            $this->created = date("Y-m-d H:i:s");
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
