<?php

namespace backend\models;

use common\models\User;
use Yii;

/**
 * This is the model class for table "{{%trang_thai_hoa_don}}".
 *
 * @property int $id
 * @property int|null $user_id
 * @property string|null $trang_thai
 * @property string|null $created
 * @property int|null $hoa_don_id
 *
 * @property HoaDon $hoaDon
 * @property User $user
 */
class TrangThaiHoaDon extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%trang_thai_hoa_don}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'hoa_don_id'], 'integer'],
            [['trang_thai'], 'string'],
            [['created'], 'safe'],
            [['hoa_don_id'], 'exist', 'skipOnError' => true, 'targetClass' => HoaDon::className(), 'targetAttribute' => ['hoa_don_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'trang_thai' => 'Trang Thai',
            'created' => 'Created',
            'hoa_don_id' => 'Hoa Don ID',
        ];
    }

    /**
     * Gets query for [[HoaDon]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getHoaDon()
    {
        return $this->hasOne(HoaDon::className(), ['id' => 'hoa_don_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    public function beforeSave($insert)
    {
        if($insert && ($this->created == '' || is_null($this->created))){
            $this->created = date("Y-m-d H:i:s");
        }
        if($this->user_id == '' || is_null($this->user_id))
            $this->user_id = Yii::$app->user->id;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function afterSave($insert, $changedAttributes)
    {
        HoaDon::updateAll(['trang_thai'=>$this->trang_thai],['id'=>$this->hoa_don_id]);
        parent::afterSave($insert, $changedAttributes);
    }
}
