<?php

namespace backend\models;

use common\models\myAPI;
use common\models\User;
use Yii;

/**
 * This is the model class for table "{{%trang_thai_giao_dich}}".
 *
 * @property int $id
 * @property string|null $trang_thai
 * @property string|null $created
 * @property int|null $user_id
 * @property int|null $giao_dich_id
 *
 * @property GiaoDich $giaoDich
 * @property User $user
 */
class TrangThaiGiaoDich extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%trang_thai_giao_dich}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['trang_thai'], 'string'],
            [['created'], 'safe'],
            [['user_id', 'giao_dich_id'], 'integer'],
            [['giao_dich_id'], 'exist', 'skipOnError' => true, 'targetClass' => GiaoDich::className(), 'targetAttribute' => ['giao_dich_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'trang_thai' => 'Trang Thai',
            'created' => 'Created',
            'user_id' => 'User ID',
            'giao_dich_id' => 'Giao Dich ID',
        ];
    }

    /**
     * Gets query for [[GiaoDich]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getGiaoDich()
    {
        return $this->hasOne(GiaoDich::className(), ['id' => 'giao_dich_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    public function beforeSave($insert)
    {
        if($insert && ($this->created == '' || is_null($this->created))){
            $this->created = date("Y-m-d H:i:s");
        }
        if($this->user_id == '' || is_null($this->user_id))
            $this->user_id = Yii::$app->user->id;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
