<?php

namespace backend\models;

use common\models\User;
use Yii;

/**
 * This is the model class for table "{{%trang_thai_don_hang}}".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $trang_thai_don_hang_old_id
 * @property string $created
 * @property integer $don_hang_id
 * @property string $ghi_chu
 * @property string $trang_thai
 *
 * @property DonHang $donHang
 * @property User $user
 */
class TrangThaiDonHang extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%trang_thai_don_hang}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'don_hang_id'], 'integer'],
            [['created', 'ghi_chu', 'trang_thai_don_hang_old_id'], 'safe'],
            [['trang_thai'], 'string'],
            [['don_hang_id'], 'exist', 'skipOnError' => true, 'targetClass' => DonHang::className(), 'targetAttribute' => ['don_hang_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'created' => 'Created',
            'don_hang_id' => 'Don Hang ID',
            'trang_thai' => 'Trang Thai',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDonHang()
    {
        return $this->hasOne(DonHang::className(), ['id' => 'don_hang_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function beforeSave($insert)
    {
        if($insert && ($this->created == '' || is_null($this->created)))
            $this->created = date("Y-m-d H:i:s");
//      $contentAPI = json_decode(file_get_contents('php://input'));
//      $this->user_id = isset($contentAPI->uid) ? $contentAPI->uid : Yii::$app->user->id;
      return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

  public function afterSave($insert, $changedAttributes)
    {
        if($insert){
            $donHang = DonHang::findOne($this->don_hang_id);
            $donHang->updateAttributes(['trang_thai' => $this->trang_thai]);
        }
      parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
