<?php

namespace backend\models;

use common\models\myActiveRecord;
use common\models\User;
use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "asv_vaitrouser".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $vai_tro_id
 *
 * @property User $user
 * @property VaiTro $vaitro0
 */
class Vaitrouser extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'qlcvsd_vaitro_user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id'], 'required'],
            [['user_id', 'vai_tro_id'], 'safe'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['vai_tro_id'], 'exist', 'skipOnError' => true, 'targetClass' => VaiTro::className(), 'targetAttribute' => ['vai_tro_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'Thành viên',
            'vaitro' => 'Vai trò',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVaitro0()
    {
        return $this->hasOne(VaiTro::className(), ['id' => 'vai_tro_id']);
    }

    public function beforeDelete()
    {
        PhanQuyen::deleteAll(['vai_tro_id' => $this->id]);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
